### ISSUE TITLE
simpler solution

### ISSUE THREAD

**Issue by tobsn** [peperzaken/iPhone-optimized-PNG-reverse-script#1]
`foreach( glob( '*.png' ) as $f ) {
    $x = `/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -revert-iphone-optimizations -q $f org.$f`;
}`

**Comment by zout** [comment]
Tnx for the feedback! We know this is the way on a mac, but... on a linux machine these tools arn't available..

**Comment by tobsn** [comment]
you sure about that comment? 
you know osx is nothing else than a linux distri... 

http://pkgs.org/download/pngcrush
